213

diff --git a/.github/workflows/publish,.yaml b/.github/workflows/publish,.yaml
--- a/.github/workflows/publish,.yaml
+++ b/.github/workflows/publish,.yaml
@@ -34,10 +34,11 @@ jobs:
         run: |
           content=`cat __about__.py`
           echo "$content"
-          regex_pattern="(\d*)\"$"
+          regex_pattern='([0-9]+\.[0-9]+\.[0-9]+)\"$'
 
-          if [[ "$content" =~ $regex_pattern ]]; then
-            echo complete match: "${BASH_REMATCH[0]}"
+          if [[ $content =~ $regex_pattern ]]; then
+              echo "${BASH_REMATCH[1]}"
           else
-            echo Failed to find version
+              echo "couldn't find version"
+              exit 1
           fi
